import os
from twilio.rest import Client


TWILIO_SANDBOX_NUMBER = f"whatsapp:+14155238886"


def send_whatsapp_alert(to_number: str, message: str) -> bool:
    """
    Sends a WhatsApp message via Twilio sandbox.

    Args:
        to_number: Farmer's phone in international format e.g. +2348012345678
        message:   The message body — generated by the pipeline

    Returns:
        True if sent successfully, False if failed
    """
    try:
        client = Client(
            os.getenv("TWILIO_ACCOUNT_SID"),
            os.getenv("TWILIO_AUTH_TOKEN")
        )

        msg = client.messages.create(
            from_=TWILIO_SANDBOX_NUMBER,
            to=f"whatsapp:{to_number}",
            body=message
        )

        print(f"[Twilio] Message sent. SID: {msg.sid}")
        return True

    except Exception as e:
        print(f"[Twilio] Failed to send message: {type(e).__name__}: {e}")
        return False


def build_alert_message(
    crop: str,
    region: str,
    current_price: float,
    currency: str,
    change_pct: float,
    harvest_urgency: str
) -> str:
    """
    Builds the WhatsApp alert message string.
    Plain language — written for the farmer, not a trader.
    """
    direction = "up" if change_pct > 0 else "down"
    urgency_line = {
        "High":   "⚠️ Sell within 48 hours — conditions are urgent.",
        "Medium": "📋 Consider selling within the week.",
        "Low":    "✅ No rush — you have time to negotiate."
    }.get(harvest_urgency, "")

    return (
        f"🌾 HarvestBridge Alert\n\n"
        f"Your {crop} in {region}:\n"
        f"💰 Current price: {current_price:,.0f} {currency}/kg\n"
        f"📈 7-day change: {abs(change_pct):.1f}% ({direction})\n\n"
        f"{urgency_line}\n\n"
        f"👉 Open HarvestBridge for your full Negotiation Brief.\n\n"
        f"Reply STOP to unsubscribe."
    )